### ISSUE TITLE
ONOFF field type not working

### ISSUE THREAD

**Issue by ck-coke** [wrongisthenewright/ebusd-configuration-ariston-bridgenet#14]
Hi, 

for all lines with onoff field type I get the following error:
`[main error] error reading config files from /etc/ebusd/: ERR: element not found, last error: ariston.csv:71: ERR: element not found, field type ONOFF in field 1`

What is the issue here and how can I solve that?

**Comment by wrongisthenewright** [comment]
You must copy on the same folder of the ariston.csv also  the _template.csv file.

It translate the 0/1 of ebusd to on)off for HA

**Comment by wrongisthenewright** [comment]
also, pay attention to caps, in my CSV onoff is lower caps, and the same is valid for _template.csv file. If you modified it to UPPER you should do it in both places (ariston.csv AND _template.csv).

**Comment by wrongisthenewright** [comment]
I'm closing this issue as solved, feel free to re-open it if needed
