### ISSUE TITLE
How to set DHW temperature.

### ISSUE THREAD

**Issue by HassioAwi** [wrongisthenewright/ebusd-configuration-ariston-bridgenet#17]
Hello. 

First, thank you for your effort in creating all of this. 

Then the problem I have is that I don't know how to adjust the DHW temperature. I have null knowledge of pregramation or MQTT.

I have the boiler connected to the boiler and when it starts I raise the water temperature and activate the comfort mode. When it is over, I leave the temperature as it was before, so as not to scorch anyone in the shower.

**Comment by wrongisthenewright** [comment]
My bad. Ysard has already done all the above, from his repo:

https://github.com/ysard/ebusd_configuration_chaffoteaux_bridgenet

in the mira_c_green.csv
```

r1,dhw,dhw_target_temp,DHW target temp,,3c,2000,6126,,s,IGN:1,,,field value = dict key for HA integration,0,s,SIN,10,°C,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```
You may need to modify these in the following version if you (like me) have a system with energy manager:

```
r,dhw,dhw_target_temp,DHW target temp,,18,2000,6126,,s,IGN:1,,,field value = dict key for HA integration,0,s,SIN,10,°C,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

then add the writing lines:

`w,dhw,dhw_target_temp,DHW target temp,,fe,2020,6126,,s,SIN,10,°C,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

create similar lines for 6226 parameter if you need to dynamically change also the reduced temp value.

I know it's a little difficult but this kind of integration is a little tricky
