### ISSUE TITLE
Know values not arriving in HA

### ISSUE THREAD

**Issue by A-J70** [wrongisthenewright/ebusd-configuration-ariston-bridgenet#22]
Hi,

I love your Ariston Ebus integration but encounter one problem: Some values do not get to HA although they are available. As soon as I use a line from read_custom.sh, all values get to HA.

For example, the calculated cost do not appear in HA. When I execute this "docker exec ebusd ebusctl read -m 0 -c energymgr heatpump_calculated_cost && sleep 5", ALL unknown values do appear in HA.

You understand that I am a complete no-no in programming but I would like to solve this! Can you give me a hint?

Thanks!

**Comment by wrongisthenewright** [comment]
Hi,
the values that doesn't show up on HA dut are readable via ebusctl read command are, for the most part, parameters that aren't transmitted explicitly on the bus. The Ariston devices don't communicate those values on the bus, thus we're unable to grab them from normal bus traffic.
We need to explicitly read them. This can be done in 2 ways, via the ebusctl read command or telling ebusd to read them every X cycles.

The first is what I've done, I've crontab-bed a script that runs every hour and read these values, my choice is motivated by the fact that these parameter seldom change and so it doesn't matter if I read them once an hour. The pro of this method is not create too much traffic on the bus, in my case, with a fairly complex setup, avoided/minimized some arbitration problem. 
The other way is instructing ebusd to read these values every X cycle, to do so you have to add a number after the "r" command in the lines that you miss and want to read, eg

`r,energymgr,heatpump_calculated_cost,Heatpump Current Calculated Cost,,18,2000,6c47,,s,IGN:1,,,,,,UIN,10,c€`

must be changed to

`r5,energymgr,heatpump_calculated_cost,Heatpump Current Calculated Cost,,18,2000,6c47,,s,IGN:1,,,,,,UIN,10,c€`

this mod cause ebusd to read the ,energymgr,heatpump_calculated_cost parameter every 5 cycles (I think).

If this sole your problem please close the issue :)

TY

**Comment by A-J70** [comment]
Wow, thanks for the answer. This seems a good explanation! I'll close the issue and give it a try.

Thanks again.
