### ISSUE TITLE
Ariston homeassistant

### ISSUE THREAD

**Issue by florin130** [wrongisthenewright/ebusd-configuration-ariston-bridgenet#8]

**Comment by wrongisthenewright** [comment]
?

**Comment by florin130** [comment]
Sorry

Il giorno gio 2 nov 2023 alle 21:55 wrongisthenewright <
***@***.***> ha scritto:

**Comment by wrongisthenewright** [comment]
Opened by error?

**Comment by florin130** [comment]
I wanted to save it in my favorites and accidentally sent a message SorryInviato da iPhoneIl giorno 2 nov 2023, alle ore 21:58, wrongisthenewright ***@***.***> ha scritto:﻿
Opened by error?
